# Modified by Ronstation contributor(s), therefore this file is licensed as MIT sublicensed with AGPL-v3.0.
- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber
  - Bagel
  - Box
  - Elkridge
  - Fland
  - Marathon
  - Packed
  - Plasma
  - Exo
# start of modifications
  - Atlas3
  - Cluster2
  - Feint
  - Saltern2
  - Oasis2
# end of modifications
